In [1]:
import numpy as np
import pandas as pd
import csv
import os
import scipy.io as sio
import h5py

### Goal of this script is to read in the FC matrices of each subject and calculate the average of it + z-transformation
Correlation of time courses were calulated in matlab - now we have correlation matrices 11883x11883  for each participant
now: sum them up for all participants, then z-transform and average
Output: averaged FC matrices (all participants) for each condition

In [2]:
path_ket = 'C:/Users/canlab/Desktop/Masterthesis_python/ket/'
path_placebo = 'C:/Users/canlab/Desktop/Masterthesis_python/placebo/'

# reading in the subject lists of placebo and ketamine
subj_ket = pd.read_csv('C:/Users/canlab/Desktop/Masterthesis_python/ket/ketamine_subjects.csv', engine='c', header = None)
subj_placebo = pd.read_csv('C:/Users/canlab/Desktop/Masterthesis_python/placebo/placebo_subjects.csv', engine='c', header = None) 

In [3]:
# dropping participant
subj_ket = subj_ket.drop([6])

In [4]:
# making an array out of it
subj_ket_new = subj_ket.iloc[:,0]
subj_ket_new.to_numpy()

array(['bg52', 'bh98', 'ce22', 'cu52', 'dp07', 'dp37', 'fy78', 'gs63',
       'hw95', 'hy97', 'ia24', 'ia45', 'ii39', 'il04', 'ju09', 'ju49',
       'jw73', 'jy99', 'kh95', 'kw91', 'op18', 'px00', 'qe30', 'sr21',
       'tt42', 'uf97', 'vg84', 'we81', 'wo30', 'ww25', 'yp84'],
      dtype=object)

In [5]:
subj_placebo_new = subj_placebo.iloc[:,0]
subj_placebo_new.to_numpy()

array(['ap75', 'bu45', 'dp20', 'dp92', 'dq56', 'dt27', 'du02', 'dw28',
       'em60', 'ew27', 'fb03', 'go11', 'ha96', 'id12', 'kd21', 'ke15',
       'kt10', 'ld98', 'me21', 'nf78', 'oz27', 'pk62', 'so93', 'tk03',
       'uh70', 'vu42', 'wn86', 'wx52', 'xp38'], dtype=object)

Read one matrix and add new matrix: so only two matrices at a time do have to be hold in memory
After all matrices are added, divide by number of participants

In [74]:
i =0
for subj in subj_ket_new:
    print(i)
    file_name = 'corr_mat_all_ses-1h_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_ket, file_name)
    # read in current subject as dataframe
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    print('current subject: ', curr_sub)
    B = np.dstack(B, curr_sub)
    i+=1
    print(subj, ': ',B)
    
    del curr_sub, curr_subj_df

MemoryError: Unable to allocate array with shape (11883, 11883, 32) and data type float64

In [73]:
del curr_subj_df

In [82]:
file_name = 'corr_mat_all_ses-1h_sub-bg52.csv'
    # path of the current subject
curr_subj_path = os.path.join(path_ket, file_name)

In [83]:
curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
curr_sub = curr_subj_df.to_numpy()

In [84]:
curr_sub

array([[ 1.        ,  0.11132463,  0.085908  , ..., -0.12008579,
        -0.04407231,  0.00784334],
       [ 0.11132463,  1.        ,  0.5114221 , ..., -0.06293206,
        -0.13480846, -0.07237615],
       [ 0.085908  ,  0.5114221 ,  1.        , ..., -0.12440866,
        -0.12202826, -0.09426148],
       ...,
       [-0.12008579, -0.06293206, -0.12440866, ...,  1.        ,
         0.62950805,  0.18061228],
       [-0.04407231, -0.13480846, -0.12202826, ...,  0.62950805,
         1.        ,  0.5181469 ],
       [ 0.00784334, -0.07237615, -0.09426148, ...,  0.18061228,
         0.5181469 ,  1.        ]])

In [85]:
z_curr_sub = np.arctanh(curr_sub)
z_curr_sub

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in arctanh
  """Entry point for launching an IPython kernel.


array([[        inf,  0.11178797,  0.08612028, ..., -0.12066808,
        -0.04410087,  0.0078435 ],
       [ 0.11178797,         inf,  0.56465368, ..., -0.06301534,
        -0.13563413, -0.07250292],
       [ 0.08612028,  0.56465368,         inf, ..., -0.12505653,
        -0.12263943, -0.09454216],
       ...,
       [-0.12066808, -0.06301534, -0.12505653, ...,         inf,
         0.74060087,  0.18261554],
       [-0.04410087, -0.13563413, -0.12263943, ...,  0.74060087,
                inf,  0.57380321],
       [ 0.0078435 , -0.07250292, -0.09454216, ...,  0.18261554,
         0.57380321,         inf]])

Looking at participant fo59

In [113]:
path_fo59 = 'C:/Users/canlab/Desktop/Masterthesis_python/ket/corr_mat_all_ses-1h_sub-fo59.csv'
fo59 = pd.read_csv(path_fo59, header=None)

In [119]:
display(fo59[666])

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
11878   NaN
11879   NaN
11880   NaN
11881   NaN
11882   NaN
Name: 666, Length: 11883, dtype: float64

In [124]:
fo59.isnull().sum()

0        1366
1        1366
2        1366
3        1366
4        1366
         ... 
11878    1366
11879    1366
11880    1366
11881    1366
11882    1366
Length: 11883, dtype: int64

In [131]:
len(subj_ket_new)

31

**Ketamine group**

In [132]:
# first matrix of zeros
A = np.zeros((11883,11883))
for subj in subj_ket_new:
    
    file_name = 'corr_mat_all_ses-1h_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_ket, file_name)
    # read in current subject as dataframe
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    #print('Row 665: ', curr_sub[665])
    # z-transform
    z_curr_sub = np.arctanh(curr_sub)
    # adding all matrices
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat[665])
    # making proper copy of mean_mat
    A = mean_mat.copy()

#np.save('C:/Users/canlab/Desktop/Masterthesis_python/ket/Ketamine_z_FC_added', mean_mat)
# calculating mean of all matrices
z_mean_mat_ket = mean_mat / len(subj_ket_new)  
np.save('C:/Users/canlab/Desktop/Masterthesis_python/ket/Ketamine_z_mean_FC', z_mean_mat_ket)


C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in arctanh
  


bg52 :  [ 0.12512317  0.12426494  0.22007977 ...  0.04345329  0.05978779
 -0.0037858 ]
bh98 :  [ 0.48835057  0.40682061  0.56450863 ...  0.11165067  0.02151507
 -0.0521737 ]
ce22 :  [ 0.65482443  0.18502532  0.23201085 ...  0.08065651 -0.05240454
  0.00999527]
cu52 :  [ 0.54124364 -0.01830814  0.39268699 ... -0.02046404 -0.21729738
  0.03987311]
dp07 :  [ 0.38973874  0.13182231  0.38709756 ... -0.14625367 -0.3153318
 -0.01874215]
dp37 :  [ 0.44646347  0.23235861  0.64405846 ...  0.19433795 -0.08306386
  0.08535656]
fy78 :  [0.45319014 0.26476258 0.6858961  ... 0.17955513 0.02437096 0.1351721 ]
gs63 :  [0.42416426 0.20194309 0.73967582 ... 0.36880598 0.13057111 0.14129544]
hw95 :  [ 0.07444833 -0.03651566  0.47066117 ...  0.2012556  -0.05333569
  0.06502622]
hy97 :  [ 0.13107729 -0.12371994  0.47643956 ...  0.1228081  -0.10157875
 -0.10641286]
ia24 :  [ 0.10173756 -0.32742415  0.59228839 ... -0.11660775 -0.29352263
 -0.12917395]
ia45 :  [ 0.06634587 -0.40933805  0.54990899 ... -0.049849

In [107]:
mean_mat_ket[665]

array([nan, nan, nan, ..., nan, nan, nan])

In [80]:
mean_mat

array([[        inf,  8.05528645,  5.74441295, ..., -0.24086645,
         0.22705125,  0.26554199],
       [ 8.05528645,         inf, 12.33882261, ..., -0.20384944,
         0.07343255, -0.63770859],
       [ 5.74441295, 12.33882261,         inf, ...,  0.51178102,
         0.26261891,  0.27211911],
       ...,
       [-0.24086645, -0.20384944,  0.51178102, ...,         inf,
        24.11022321, 10.79336453],
       [ 0.22705125,  0.07343255,  0.26261891, ..., 24.11022321,
                inf, 24.37985483],
       [ 0.26554199, -0.63770859,  0.27211911, ..., 10.79336453,
        24.37985483,         inf]])

In [81]:
mean_mat_ket

array([[        inf,  0.2517277 ,  0.1795129 , ..., -0.00752708,
         0.00709535,  0.00829819],
       [ 0.2517277 ,         inf,  0.38558821, ..., -0.0063703 ,
         0.00229477, -0.01992839],
       [ 0.1795129 ,  0.38558821,         inf, ...,  0.01599316,
         0.00820684,  0.00850372],
       ...,
       [-0.00752708, -0.0063703 ,  0.01599316, ...,         inf,
         0.75344448,  0.33729264],
       [ 0.00709535,  0.00229477,  0.00820684, ...,  0.75344448,
                inf,  0.76187046],
       [ 0.00829819, -0.01992839,  0.00850372, ...,  0.33729264,
         0.76187046,         inf]])

In [105]:
del A, mean_mat, curr_sub, curr_subj_df, mean_mat_ket

**Placebo group**

In [92]:
# first matrix of zeros
A = np.zeros((11883,11883))
for subj in subj_placebo_new:
    
    file_name = 'corr_mat_all_ses-1h_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_placebo, file_name)
    # read in current subject as dataframe
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    # Fisher transform
    z_curr_sub = np.arctanh(curr_sub)
    # adding
    mean_mat = np.add(z_curr_sub, A)
    
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()
    
# saving matrices    
np.save('C:/Users/canlab/Desktop/Masterthesis_python/placebo/Placebo_z_FC_added', mean_mat)
mean_mat_placebo = mean_mat / len(subj_placebo_new) 
np.save('C:/Users/canlab/Desktop/Masterthesis_python/placebo/Placebo_z_mean_FC', mean_mat_placebo)


C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in arctanh
  del sys.path[0]


ap75 :  [[        inf  0.25356847  0.10652066 ... -0.05860069  0.00755761
   0.00681601]
 [ 0.25356847         inf  0.14989422 ... -0.02080345  0.01802287
   0.00367747]
 [ 0.10652066  0.14989422         inf ... -0.04600126 -0.04034335
  -0.02790355]
 ...
 [-0.05860069 -0.02080345 -0.04600126 ...         inf  0.39889887
   0.1012195 ]
 [ 0.00755761  0.01802287 -0.04034335 ...  0.39889887         inf
   0.57786457]
 [ 0.00681601  0.00367747 -0.02790355 ...  0.1012195   0.57786457
          inf]]
bu45 :  [[        inf  0.54161354  0.34901272 ...  0.06351853  0.14197275
   0.07751714]
 [ 0.54161354         inf  0.59965594 ...  0.2055259   0.20501842
   0.13756301]
 [ 0.34901272  0.59965594         inf ...  0.11881296 -0.03357576
   0.09539053]
 ...
 [ 0.06351853  0.2055259   0.11881296 ...         inf  1.0865531
   0.37662003]
 [ 0.14197275  0.20501842 -0.03357576 ...  1.0865531          inf
   1.26386305]
 [ 0.07751714  0.13756301  0.09539053 ...  0.37662003  1.26386305
          inf]]
d

kt10 :  [[            inf  4.42132398e+00  1.63274171e+00 ...  4.56443921e-01
   3.25964397e-01  3.64149598e-01]
 [ 4.42132398e+00             inf  4.62189754e+00 ...  4.12578618e-01
   1.23305137e-01 -9.03314632e-02]
 [ 1.63274171e+00  4.62189754e+00             inf ... -9.45089762e-03
  -2.99385842e-01  4.89811629e-02]
 ...
 [ 4.56443921e-01  4.12578618e-01 -9.45089762e-03 ...             inf
   1.33648049e+01  6.11769144e+00]
 [ 3.25964397e-01  1.23305137e-01 -2.99385842e-01 ...  1.33648049e+01
              inf  1.38768574e+01]
 [ 3.64149598e-01 -9.03314632e-02  4.89811629e-02 ...  6.11769144e+00
   1.38768574e+01             inf]]
ld98 :  [[        inf  4.3820182   1.712912   ...  0.4480968   0.28426435
   0.35010971]
 [ 4.3820182          inf  4.93357138 ...  0.34468025  0.13359108
  -0.08952342]
 [ 1.712912    4.93357138         inf ... -0.03172166 -0.32645601
   0.0449885 ]
 ...
 [ 0.4480968   0.34468025 -0.03172166 ...         inf 14.00854965
   6.450963  ]
 [ 0.28426435  0.13

In [100]:
del A,mean_mat, curr_sub, curr_subj_df, mean_mat_placebo, z_curr_sub

**Baseline**

concatenate the list of participants

In [10]:
path_baseline = 'C:/Users/canlab/Desktop/Masterthesis_python/baseline'

In [135]:
subjects = np.append(subj_placebo_new, subj_ket_new)
subjects
#len(subjects)

array(['ap75', 'bu45', 'dp20', 'dp92', 'dq56', 'dt27', 'du02', 'dw28',
       'em60', 'ew27', 'fb03', 'go11', 'ha96', 'id12', 'kd21', 'ke15',
       'kt10', 'ld98', 'me21', 'nf78', 'oz27', 'pk62', 'so93', 'tk03',
       'uh70', 'vu42', 'wn86', 'wx52', 'xp38', 'bg52', 'bh98', 'ce22',
       'cu52', 'dp07', 'dp37', 'fy78', 'gs63', 'hw95', 'hy97', 'ia24',
       'ia45', 'ii39', 'il04', 'ju09', 'ju49', 'jw73', 'jy99', 'kh95',
       'kw91', 'op18', 'px00', 'qe30', 'sr21', 'tt42', 'uf97', 'vg84',
       'we81', 'wo30', 'ww25', 'yp84'], dtype=object)

In [137]:
# first matrix of zeros
A = np.zeros((11883,11883))
for subj in subjects:
    
    file_name = 'corr_mat_all_ses-baseline_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_baseline, file_name)
    # read in current subject as dataframe
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    z_curr_sub = np.arctanh(curr_sub)
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()

# saving matrices 
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_z_FC_added', mean_mat)
mean_mat_baseline = mean_mat / len(subjects)  
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_z_mean_FC', mean_mat_baseline)

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in arctanh
  if sys.path[0] == '':


ap75 :  [[        inf  0.23671998 -0.0079099  ... -0.02840506  0.00270642
  -0.17666799]
 [ 0.23671998         inf  0.25489854 ...  0.08735687  0.11873444
  -0.0772284 ]
 [-0.0079099   0.25489854         inf ... -0.05737735 -0.00104696
  -0.01665306]
 ...
 [-0.02840506  0.08735687 -0.05737735 ...         inf  0.43622304
  -0.01454103]
 [ 0.00270642  0.11873444 -0.00104696 ...  0.43622304         inf
   0.39024565]
 [-0.17666799 -0.0772284  -0.01665306 ... -0.01454103  0.39024565
          inf]]
bu45 :  [[        inf  0.32685243  0.15825733 ...  0.04335409  0.03063823
  -0.25325548]
 [ 0.32685243         inf  0.70967799 ...  0.18469386  0.1580585
  -0.12130864]
 [ 0.15825733  0.70967799         inf ...  0.04334701 -0.04033846
   0.00868039]
 ...
 [ 0.04335409  0.18469386  0.04334701 ...         inf  1.1588654
   0.06181893]
 [ 0.03063823  0.1580585  -0.04033846 ...  1.1588654          inf
   0.87027397]
 [-0.25325548 -0.12130864  0.00868039 ...  0.06181893  0.87027397
          inf]]
dp

kt10 :  [[        inf  4.92618838  2.22489424 ...  0.16898086  0.2034853
  -0.24977698]
 [ 4.92618838         inf  4.77349746 ...  0.32041771  0.102379
  -0.52021839]
 [ 2.22489424  4.77349746         inf ...  0.31532015  0.20986071
  -0.19083224]
 ...
 [ 0.16898086  0.32041771  0.31532015 ...         inf 12.53166276
   4.03945774]
 [ 0.2034853   0.102379    0.20986071 ... 12.53166276         inf
  11.61432821]
 [-0.24977698 -0.52021839 -0.19083224 ...  4.03945774 11.61432821
          inf]]
ld98 :  [[        inf  5.38234343  2.29059641 ...  0.1373121   0.11695534
  -0.33577557]
 [ 5.38234343         inf  5.05861606 ...  0.38454539  0.20682131
  -0.43315818]
 [ 2.29059641  5.05861606         inf ...  0.32339715  0.28404254
  -0.15391387]
 ...
 [ 0.1373121   0.38454539  0.32339715 ...         inf 13.12978725
   4.18117813]
 [ 0.11695534  0.20682131  0.28404254 ... 13.12978725         inf
  12.09607208]
 [-0.33577557 -0.43315818 -0.15391387 ...  4.18117813 12.09607208
          inf]]
me2

cu52 :  [[        inf  8.25675584  3.35481811 ...  0.0337701   0.36058567
  -0.42737403]
 [ 8.25675584         inf  7.836153   ...  0.14667054 -0.0747893
  -0.21020024]
 [ 3.35481811  7.836153           inf ...  0.11984371  0.32877787
  -0.26479319]
 ...
 [ 0.0337701   0.14667054  0.11984371 ...         inf 25.25366729
   9.24071313]
 [ 0.36058567 -0.0747893   0.32877787 ... 25.25366729         inf
  23.30031384]
 [-0.42737403 -0.21020024 -0.26479319 ...  9.24071313 23.30031384
          inf]]
dp07 :  [[        inf  8.38864138  3.36790239 ... -0.02714386  0.29785938
  -0.43670204]
 [ 8.38864138         inf  8.31278913 ...  0.23678763 -0.06204844
  -0.15404739]
 [ 3.36790239  8.31278913         inf ...  0.15728976  0.38200795
  -0.20063659]
 ...
 [-0.02714386  0.23678763  0.15728976 ...         inf 26.30573228
  10.01600725]
 [ 0.29785938 -0.06204844  0.38200795 ... 26.30573228         inf
  24.33305197]
 [-0.43670204 -0.15404739 -0.20063659 ... 10.01600725 24.33305197
          inf]]
d

kh95 :  [[        inf 10.5858627   6.05534186 ... -0.15188197  0.09505002
  -0.16686336]
 [10.5858627          inf 12.2358254  ...  0.27239503  0.0882956
  -0.52626471]
 [ 6.05534186 12.2358254          inf ... -0.48388746  0.2089226
  -0.46370504]
 ...
 [-0.15188197  0.27239503 -0.48388746 ...         inf 36.63448466
  14.57739263]
 [ 0.09505002  0.0882956   0.2089226  ... 36.63448466         inf
  35.00447535]
 [-0.16686336 -0.52626471 -0.46370504 ... 14.57739263 35.00447535
          inf]]
kw91 :  [[        inf 10.4760118   6.01270856 ... -0.0732655   0.08011122
  -0.18867784]
 [10.4760118          inf 12.48772684 ...  0.31089967  0.15924991
  -0.46092707]
 [ 6.01270856 12.48772684         inf ... -0.55937699  0.15847257
  -0.5240578 ]
 ...
 [-0.0732655   0.31089967 -0.55937699 ...         inf 37.24035245
  14.73965556]
 [ 0.08011122  0.15924991  0.15847257 ... 37.24035245         inf
  35.83553299]
 [-0.18867784 -0.46092707 -0.5240578  ... 14.73965556 35.83553299
          inf]]
op

In [25]:
del mean_mat

In [77]:
B = [[1 ,0.5],
    [.6, .1],
    [-.7, -.4]]
C = [[3, 4], 
    [5, 6],
    [1, 5]]

In [78]:
np.arctanh(B)

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in arctanh
  """Entry point for launching an IPython kernel.


array([[        inf,  0.54930614],
       [ 0.69314718,  0.10033535],
       [-0.86730053, -0.42364893]])

In [30]:
B+C

[[1, 2], [3, 5], [3, 4], [5, 6]]

In [39]:
B[1][1]

5

In [16]:
np.add(B,C)

array([[ 4,  6],
       [ 8, 11]])

In [17]:
np.add(B,C)* (0.5)

array([[2. , 3. ],
       [4. , 5.5]])

In [45]:
D = np.zeros((2,3,2))
D

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [46]:

D[:][:][0] = B

In [47]:
D

array([[[1., 2.],
        [3., 5.],
        [2., 6.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [48]:
D[:][:][1] = C

In [49]:
D

array([[[1., 2.],
        [3., 5.],
        [2., 6.]],

       [[3., 4.],
        [5., 6.],
        [1., 5.]]])

### New baseline: Split for ketamine and placebo

Ketamine baseline

In [6]:
subj_ket_new

0     bg52
1     bh98
2     ce22
3     cu52
4     dp07
5     dp37
7     fy78
8     gs63
9     hw95
10    hy97
11    ia24
12    ia45
13    ii39
14    il04
15    ju09
16    ju49
17    jw73
18    jy99
19    kh95
20    kw91
21    op18
22    px00
23    qe30
24    sr21
25    tt42
26    uf97
27    vg84
28    we81
29    wo30
30    ww25
31    yp84
Name: 0, dtype: object

In [11]:
# first matrix of zeros
A = np.zeros((11883,11883))
count=0
for subj in subj_ket_new:
    # only loads ketamine subjects in baseline
    file_name = 'corr_mat_all_ses-baseline_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_baseline, file_name)
    # read in current subject as dataframe
    # correlated timecourses of each participant
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    z_curr_sub = np.arctanh(curr_sub)
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()
    count+=1
    print('Count: ', count)
    
# saving matrices 
#np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_z_FC_added', mean_mat)
mean_mat_baseline = mean_mat / len(subjects)  
#np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_z_mean_FC', mean_mat_baseline)

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in arctanh
  del sys.path[0]


bg52 :  [[        inf -0.01653116  0.02026774 ...  0.07604244  0.08006396
   0.01105546]
 [-0.01653116         inf  0.34124136 ...  0.04626776  0.00969651
  -0.0297769 ]
 [ 0.02026774  0.34124136         inf ...  0.01523179  0.00663131
   0.02678193]
 ...
 [ 0.07604244  0.04626776  0.01523179 ...         inf  0.9371408
   0.27801778]
 [ 0.08006396  0.00969651  0.00663131 ...  0.9371408          inf
   0.7310213 ]
 [ 0.01105546 -0.0297769   0.02678193 ...  0.27801778  0.7310213
          inf]]
Count:  1
bh98 :  [[        inf -0.00749729  0.107379   ...  0.1098616   0.16332627
   0.08583605]
 [-0.00749729         inf  0.60906599 ... -0.09393487 -0.07513643
  -0.08695777]
 [ 0.107379    0.60906599         inf ... -0.01868444  0.16605038
   0.1796998 ]
 ...
 [ 0.1098616  -0.09393487 -0.01868444 ...         inf  1.46660938
   0.26534902]
 [ 0.16332627 -0.07513643  0.16605038 ...  1.46660938         inf
   1.42986823]
 [ 0.08583605 -0.08695777  0.1796998  ...  0.26534902  1.42986823
        

Count:  16
jw73 :  [[            inf  2.35417525e+00  2.78682539e+00 ... -4.65184051e-01
  -5.26589036e-01 -7.39236521e-02]
 [ 2.35417525e+00             inf  5.14228062e+00 ...  7.86633560e-02
   5.30405138e-02 -3.07485154e-01]
 [ 2.78682539e+00  5.14228062e+00             inf ... -3.90644116e-01
   6.97991099e-03  6.48866603e-02]
 ...
 [-4.65184051e-01  7.86633560e-02 -3.90644116e-01 ...             inf
   1.27658094e+01  5.21661697e+00]
 [-5.26589036e-01  5.30405138e-02  6.97991099e-03 ...  1.27658094e+01
              inf  1.24420414e+01]
 [-7.39236521e-02 -3.07485154e-01  6.48866603e-02 ...  5.21661697e+00
   1.24420414e+01             inf]]
Count:  17
jy99 :  [[        inf  2.50032406  2.75214822 ... -0.44856553 -0.48266398
   0.24601661]
 [ 2.50032406         inf  5.16180083 ...  0.017854   -0.07049223
  -0.58580637]
 [ 2.75214822  5.16180083         inf ... -0.50988145  0.18029051
   0.12046222]
 ...
 [-0.44856553  0.017854   -0.50988145 ...         inf 13.29333928
   5.3009065

Count:  31


NameError: name 'subjects' is not defined

In [ ]:
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_ket_z_FC_added', mean_mat)
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_ket_z_mean_FC', mean_mat_baseline)

In [12]:
mean_mat_b_k = mean_mat / len(subj_ket_new)
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_ket_z_mean_FC', mean_mat_b_k)

In [14]:
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_ket_z_FC_added', mean_mat)

In [15]:
len(subj_ket_new)

31

In [17]:
del A, mean_mat, curr_sub, curr_subj_df, mean_mat_b_k

NameError: name 'A' is not defined

Placebo baseline

In [18]:
# first matrix of zeros
A = np.zeros((11883,11883))
count=0
for subj in subj_placebo_new :
    # only loads ketamine subjects in baseline
    file_name = 'corr_mat_all_ses-baseline_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_baseline, file_name)
    # read in current subject as dataframe
    # correlated timecourses of each participant
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    z_curr_sub = np.arctanh(curr_sub)
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()
    count+=1
    print('Count: ', count)
    
# saving matrices 
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_p_z_FC_added', mean_mat)
mean_mat_baseline_p = mean_mat / len(subj_placebo_new)  
np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_p_z_mean_FC', mean_mat_baseline_p)

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in arctanh
  


ap75 :  [[        inf  0.23671998 -0.0079099  ... -0.02840506  0.00270642
  -0.17666799]
 [ 0.23671998         inf  0.25489854 ...  0.08735687  0.11873444
  -0.0772284 ]
 [-0.0079099   0.25489854         inf ... -0.05737735 -0.00104696
  -0.01665306]
 ...
 [-0.02840506  0.08735687 -0.05737735 ...         inf  0.43622304
  -0.01454103]
 [ 0.00270642  0.11873444 -0.00104696 ...  0.43622304         inf
   0.39024565]
 [-0.17666799 -0.0772284  -0.01665306 ... -0.01454103  0.39024565
          inf]]
Count:  1
bu45 :  [[        inf  0.32685243  0.15825733 ...  0.04335409  0.03063823
  -0.25325548]
 [ 0.32685243         inf  0.70967799 ...  0.18469386  0.1580585
  -0.12130864]
 [ 0.15825733  0.70967799         inf ...  0.04334701 -0.04033846
   0.00868039]
 ...
 [ 0.04335409  0.18469386  0.04334701 ...         inf  1.1588654
   0.06181893]
 [ 0.03063823  0.1580585  -0.04033846 ...  1.1588654          inf
   0.87027397]
 [-0.25325548 -0.12130864  0.00868039 ...  0.06181893  0.87027397
        

Count:  16
kt10 :  [[        inf  4.92618838  2.22489424 ...  0.16898086  0.2034853
  -0.24977698]
 [ 4.92618838         inf  4.77349746 ...  0.32041771  0.102379
  -0.52021839]
 [ 2.22489424  4.77349746         inf ...  0.31532015  0.20986071
  -0.19083224]
 ...
 [ 0.16898086  0.32041771  0.31532015 ...         inf 12.53166276
   4.03945774]
 [ 0.2034853   0.102379    0.20986071 ... 12.53166276         inf
  11.61432821]
 [-0.24977698 -0.52021839 -0.19083224 ...  4.03945774 11.61432821
          inf]]
Count:  17
ld98 :  [[        inf  5.38234343  2.29059641 ...  0.1373121   0.11695534
  -0.33577557]
 [ 5.38234343         inf  5.05861606 ...  0.38454539  0.20682131
  -0.43315818]
 [ 2.29059641  5.05861606         inf ...  0.32339715  0.28404254
  -0.15391387]
 ...
 [ 0.1373121   0.38454539  0.32339715 ...         inf 13.12978725
   4.18117813]
 [ 0.11695534  0.20682131  0.28404254 ... 13.12978725         inf
  12.09607208]
 [-0.33577557 -0.43315818 -0.15391387 ...  4.18117813 12.096072

In [19]:
mean_mat_baseline_p

array([[        inf,  0.26829097,  0.10764058, ...,  0.00862008,
         0.01913917, -0.01481287],
       [ 0.26829097,         inf,  0.23053835, ...,  0.01211898,
         0.0069263 ,  0.00308682],
       [ 0.10764058,  0.23053835,         inf, ...,  0.01053156,
         0.0096468 , -0.01151348],
       ...,
       [ 0.00862008,  0.01211898,  0.01053156, ...,         inf,
         0.75688051,  0.28337023],
       [ 0.01913917,  0.0069263 ,  0.0096468 , ...,  0.75688051,
                inf,  0.70104278],
       [-0.01481287,  0.00308682, -0.01151348, ...,  0.28337023,
         0.70104278,         inf]])

In [20]:
mean_mat

array([[        inf,  7.78043803,  3.12157678, ...,  0.24998227,
         0.555036  , -0.42957322],
       [ 7.78043803,         inf,  6.68561218, ...,  0.35145038,
         0.20086272,  0.08951791],
       [ 3.12157678,  6.68561218,         inf, ...,  0.30541521,
         0.2797571 , -0.33389104],
       ...,
       [ 0.24998227,  0.35145038,  0.30541521, ...,         inf,
        21.94953487,  8.2177368 ],
       [ 0.555036  ,  0.20086272,  0.2797571 , ..., 21.94953487,
                inf, 20.33024056],
       [-0.42957322,  0.08951791, -0.33389104, ...,  8.2177368 ,
        20.33024056,         inf]])