### Goal of this script is to read in the FC matrices of each subject and calculate the average of it + z-transformation
Re-doing of analysis: 20.04.20

Correlation of time courses were calulated in matlab - now we have correlation matrices 11883x11883  for each participant
now: sum them up for all participants, then z-transform and average
Output: averaged FC matrices (all participants) for each condition

In [7]:
import numpy as np
import pandas as pd
import csv
import os
import scipy.io as sio

In [16]:
path_ket = 'C:/Users/canlab/Desktop/Masterthesis_python/ket/'
path_placebo = 'C:/Users/canlab/Desktop/Masterthesis_python/placebo/'

# reading in the subject lists of placebo and ketamine
subj_ket = pd.read_csv('C:/Users/canlab/Desktop/Masterthesis_python/ket/ketamine_subjects.csv', engine='c', header = None)
subj_placebo = pd.read_csv('C:/Users/canlab/Desktop/Masterthesis_python/placebo/placebo_subjects.csv', engine='c', header = None) 

In [17]:
subj_ket

0      1
0   bg52  Verum
1   bh98  Verum
2   ce22  Verum
3   cu52  Verum
4   dp07  Verum
5   dp37  Verum
6   fo59  Verum
7   fy78  Verum
8   gs63  Verum
9   hw95  Verum
10  hy97  Verum
11  ia24  Verum
12  ia45  Verum
13  ii39  Verum
14  il04  Verum
15  ju09  Verum
16  ju49  Verum
17  jw73  Verum
18  kd21  Verum
19  kh95  Verum
20  kw91  Verum
21  op18  Verum
22  px00  Verum
23  qe30  Verum
24  sr21  Verum
25  tt42  Verum
26  uf97  Verum
27  vg84  Verum
28  we81  Verum
29  wo30  Verum
30  ww25  Verum
31  yp84  Verum

In [18]:
subj_placebo

0        1
0   ap75  Placebo
1   bu45  Placebo
2   dp20  Placebo
3   dp92  Placebo
4   dq56  Placebo
5   dt27  Placebo
6   du02  Placebo
7   dw28  Placebo
8   em60  Placebo
9   ew27  Placebo
10  fb03  Placebo
11  go11  Placebo
12  ha96  Placebo
13  id12  Placebo
14  jy99  Placebo
15  ke15  Placebo
16  kt10  Placebo
17  ld98  Placebo
18  me21  Placebo
19  nf78  Placebo
20  oz27  Placebo
21  pk62  Placebo
22  so93  Placebo
23  tk03  Placebo
24  uh70  Placebo
25  vu42  Placebo
26  wn86  Placebo
27  wx52  Placebo
28  xp38  Placebo

In [19]:
# dropping participant fo59 due to errors in signal
subj_ket = subj_ket.drop([6])

In [20]:
# making an array out of it
subj_ket_new = subj_ket.iloc[:,0]
subj_ket_new.to_numpy()

array(['bg52', 'bh98', 'ce22', 'cu52', 'dp07', 'dp37', 'fy78', 'gs63',
       'hw95', 'hy97', 'ia24', 'ia45', 'ii39', 'il04', 'ju09', 'ju49',
       'jw73', 'kd21', 'kh95', 'kw91', 'op18', 'px00', 'qe30', 'sr21',
       'tt42', 'uf97', 'vg84', 'we81', 'wo30', 'ww25', 'yp84'],
      dtype=object)

**Save new ketamine subject list**

In [21]:
subj_ket_new.to_pickle('C:/Users/canlab/Desktop/Masterthesis_python/New_ketamine_subject_list')

In [22]:
subj_ket_new

0     bg52
1     bh98
2     ce22
3     cu52
4     dp07
5     dp37
7     fy78
8     gs63
9     hw95
10    hy97
11    ia24
12    ia45
13    ii39
14    il04
15    ju09
16    ju49
17    jw73
18    kd21
19    kh95
20    kw91
21    op18
22    px00
23    qe30
24    sr21
25    tt42
26    uf97
27    vg84
28    we81
29    wo30
30    ww25
31    yp84
Name: 0, dtype: object

In [15]:
len(subj_ket_new)

31

In [24]:
subj_placebo_new = subj_placebo.iloc[:,0]
subj_placebo_new.to_numpy()

array(['ap75', 'bu45', 'dp20', 'dp92', 'dq56', 'dt27', 'du02', 'dw28',
       'em60', 'ew27', 'fb03', 'go11', 'ha96', 'id12', 'jy99', 'ke15',
       'kt10', 'ld98', 'me21', 'nf78', 'oz27', 'pk62', 'so93', 'tk03',
       'uh70', 'vu42', 'wn86', 'wx52', 'xp38'], dtype=object)

In [25]:
subj_placebo_new.to_pickle('C:/Users/canlab/Desktop/Masterthesis_python/New_placebo_subject_list')

Read one matrix and add new matrix: so only two matrices at a time do have to be hold in memory
After all matrices are added, divide by number of participants

In [27]:
# new saving path
new_path_k='C:/Users/canlab/Desktop/Masterthesis_python/ReDoneAnalysis20200420/Ket'
new_path_p='C:/Users/canlab/Desktop/Masterthesis_python/ReDoneAnalysis20200420/Placebo'


**Ketamine group**

In [32]:
# first matrix of zeros
A = np.zeros((11883,11883))
for subj in subj_ket_new:
    
    file_name = 'corr_mat_all_ses-1h_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_ket, file_name)
    # read in current subject as dataframe
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    #print('Row 665: ', curr_sub[665])
    # z-transform
    z_curr_sub = np.arctanh(curr_sub)
    # adding all matrices
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat[665])
    # making proper copy of mean_mat
    A = mean_mat.copy()

#np.save('C:/Users/canlab/Desktop/Masterthesis_python/ket/Ketamine_z_FC_added', mean_mat)
# calculating mean of all matrices
z_mean_mat_ket = mean_mat / len(subj_ket_new)  
np.save('C:/Users/canlab/Desktop/Masterthesis_python/ReDoneAnalysis20200420/Ket/Ketamine_z_mean_FC', z_mean_mat_ket)


C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in arctanh
  


bg52 :  [ 0.12512317  0.12426494  0.22007977 ...  0.04345329  0.05978779
 -0.0037858 ]
bh98 :  [ 0.48835057  0.40682061  0.56450863 ...  0.11165067  0.02151507
 -0.0521737 ]
ce22 :  [ 0.65482443  0.18502532  0.23201085 ...  0.08065651 -0.05240454
  0.00999527]
cu52 :  [ 0.54124364 -0.01830814  0.39268699 ... -0.02046404 -0.21729738
  0.03987311]
dp07 :  [ 0.38973874  0.13182231  0.38709756 ... -0.14625367 -0.3153318
 -0.01874215]
dp37 :  [ 0.44646347  0.23235861  0.64405846 ...  0.19433795 -0.08306386
  0.08535656]
fy78 :  [0.45319014 0.26476258 0.6858961  ... 0.17955513 0.02437096 0.1351721 ]
gs63 :  [0.42416426 0.20194309 0.73967582 ... 0.36880598 0.13057111 0.14129544]
hw95 :  [ 0.07444833 -0.03651566  0.47066117 ...  0.2012556  -0.05333569
  0.06502622]
hy97 :  [ 0.13107729 -0.12371994  0.47643956 ...  0.1228081  -0.10157875
 -0.10641286]
ia24 :  [ 0.10173756 -0.32742415  0.59228839 ... -0.11660775 -0.29352263
 -0.12917395]
ia45 :  [ 0.06634587 -0.40933805  0.54990899 ... -0.049849

In [107]:
mean_mat_ket[665]

array([nan, nan, nan, ..., nan, nan, nan])

In [80]:
mean_mat

array([[        inf,  8.05528645,  5.74441295, ..., -0.24086645,
         0.22705125,  0.26554199],
       [ 8.05528645,         inf, 12.33882261, ..., -0.20384944,
         0.07343255, -0.63770859],
       [ 5.74441295, 12.33882261,         inf, ...,  0.51178102,
         0.26261891,  0.27211911],
       ...,
       [-0.24086645, -0.20384944,  0.51178102, ...,         inf,
        24.11022321, 10.79336453],
       [ 0.22705125,  0.07343255,  0.26261891, ..., 24.11022321,
                inf, 24.37985483],
       [ 0.26554199, -0.63770859,  0.27211911, ..., 10.79336453,
        24.37985483,         inf]])

In [81]:
mean_mat_ket

array([[        inf,  0.2517277 ,  0.1795129 , ..., -0.00752708,
         0.00709535,  0.00829819],
       [ 0.2517277 ,         inf,  0.38558821, ..., -0.0063703 ,
         0.00229477, -0.01992839],
       [ 0.1795129 ,  0.38558821,         inf, ...,  0.01599316,
         0.00820684,  0.00850372],
       ...,
       [-0.00752708, -0.0063703 ,  0.01599316, ...,         inf,
         0.75344448,  0.33729264],
       [ 0.00709535,  0.00229477,  0.00820684, ...,  0.75344448,
                inf,  0.76187046],
       [ 0.00829819, -0.01992839,  0.00850372, ...,  0.33729264,
         0.76187046,         inf]])

In [34]:
del A, mean_mat, curr_sub, curr_subj_df, mean_mat_ket

NameError: name 'mean_mat_ket' is not defined

**Placebo group**

In [35]:
# first matrix of zeros
A = np.zeros((11883,11883))
for subj in subj_placebo_new:
    
    file_name = 'corr_mat_all_ses-1h_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_placebo, file_name)
    # read in current subject as dataframe
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    # Fisher transform
    z_curr_sub = np.arctanh(curr_sub)
    # adding
    mean_mat = np.add(z_curr_sub, A)
    
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()
    
# saving matrices    
#np.save('C:/Users/canlab/Desktop/Masterthesis_python/placebo/Placebo_z_FC_added', mean_mat)
mean_mat_placebo = mean_mat / len(subj_placebo_new) 
np.save('C:/Users/canlab/Desktop/Masterthesis_python/ReDoneAnalysis20200420/Placebo/Placebo_z_mean_FC', mean_mat_placebo)


C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in arctanh
  del sys.path[0]


ap75 :  [[        inf  0.25356847  0.10652066 ... -0.05860069  0.00755761
   0.00681601]
 [ 0.25356847         inf  0.14989422 ... -0.02080345  0.01802287
   0.00367747]
 [ 0.10652066  0.14989422         inf ... -0.04600126 -0.04034335
  -0.02790355]
 ...
 [-0.05860069 -0.02080345 -0.04600126 ...         inf  0.39889887
   0.1012195 ]
 [ 0.00755761  0.01802287 -0.04034335 ...  0.39889887         inf
   0.57786457]
 [ 0.00681601  0.00367747 -0.02790355 ...  0.1012195   0.57786457
          inf]]
bu45 :  [[        inf  0.54161354  0.34901272 ...  0.06351853  0.14197275
   0.07751714]
 [ 0.54161354         inf  0.59965594 ...  0.2055259   0.20501842
   0.13756301]
 [ 0.34901272  0.59965594         inf ...  0.11881296 -0.03357576
   0.09539053]
 ...
 [ 0.06351853  0.2055259   0.11881296 ...         inf  1.0865531
   0.37662003]
 [ 0.14197275  0.20501842 -0.03357576 ...  1.0865531          inf
   1.26386305]
 [ 0.07751714  0.13756301  0.09539053 ...  0.37662003  1.26386305
          inf]]
d

kt10 :  [[        inf  4.36060419  1.63010218 ...  0.20039752  0.123383
   0.18189591]
 [ 4.36060419         inf  4.62618828 ...  0.34331599  0.12661792
  -0.16563789]
 [ 1.63010218  4.62618828         inf ... -0.21737318 -0.6263635
  -0.21340732]
 ...
 [ 0.20039752  0.34331599 -0.21737318 ...         inf 12.93625172
   5.8346066 ]
 [ 0.123383    0.12661792 -0.6263635  ... 12.93625172         inf
  13.56873834]
 [ 0.18189591 -0.16563789 -0.21340732 ...  5.8346066  13.56873834
          inf]]
ld98 :  [[        inf  4.3212984   1.71027248 ...  0.1920504   0.08168296
   0.16785602]
 [ 4.3212984          inf  4.93786212 ...  0.27541762  0.13690386
  -0.16482985]
 [ 1.71027248  4.93786212         inf ... -0.23964394 -0.65343366
  -0.21739999]
 ...
 [ 0.1920504   0.27541762 -0.23964394 ...         inf 13.57999648
   6.16787816]
 [ 0.08168296  0.13690386 -0.65343366 ... 13.57999648         inf
  14.30631984]
 [ 0.16785602 -0.16482985 -0.21739999 ...  6.16787816 14.30631984
          inf]]
me2

In [100]:
del A,mean_mat, curr_sub, curr_subj_df, mean_mat_placebo, z_curr_sub

### Baseline: Split for ketamine and placebo

Ketamine baseline

In [33]:
path_baseline='C:/Users/canlab/Desktop/Masterthesis_python/baseline'

In [37]:
# first matrix of zeros
A = np.zeros((11883,11883))
count=0
for subj in subj_ket_new:
    # only loads ketamine subjects in baseline
    file_name = 'corr_mat_all_ses-baseline_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_baseline, file_name)
    # read in current subject as dataframe
    # correlated timecourses of each participant
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    z_curr_sub = np.arctanh(curr_sub)
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()
    count+=1
    print(subj, ': ' , mean_mat)
    
# saving matrices 
#np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_z_FC_added', mean_mat)
mean_mat_baseline = mean_mat / len(subj_ket_new)  
np.save('C:/Users/canlab/Desktop/Masterthesis_python/ReDoneAnalysis20200420/Ket/Baseline_k_z_mean_FC', mean_mat_baseline)

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in arctanh
  


bg52 :  [[        inf -0.01653116  0.02026774 ...  0.07604244  0.08006396
   0.01105546]
 [-0.01653116         inf  0.34124136 ...  0.04626776  0.00969651
  -0.0297769 ]
 [ 0.02026774  0.34124136         inf ...  0.01523179  0.00663131
   0.02678193]
 ...
 [ 0.07604244  0.04626776  0.01523179 ...         inf  0.9371408
   0.27801778]
 [ 0.08006396  0.00969651  0.00663131 ...  0.9371408          inf
   0.7310213 ]
 [ 0.01105546 -0.0297769   0.02678193 ...  0.27801778  0.7310213
          inf]]
bg52 :  [[        inf -0.01653116  0.02026774 ...  0.07604244  0.08006396
   0.01105546]
 [-0.01653116         inf  0.34124136 ...  0.04626776  0.00969651
  -0.0297769 ]
 [ 0.02026774  0.34124136         inf ...  0.01523179  0.00663131
   0.02678193]
 ...
 [ 0.07604244  0.04626776  0.01523179 ...         inf  0.9371408
   0.27801778]
 [ 0.08006396  0.00969651  0.00663131 ...  0.9371408          inf
   0.7310213 ]
 [ 0.01105546 -0.0297769   0.02678193 ...  0.27801778  0.7310213
          inf]]
bh98

hw95 :  [[        inf  1.13447454  1.61853942 ... -0.35251809 -0.53520204
  -0.17809181]
 [ 1.13447454         inf  2.96866629 ... -0.11849937 -0.26887227
  -0.4484676 ]
 [ 1.61853942  2.96866629         inf ... -0.09369672  0.15747429
   0.21385675]
 ...
 [-0.35251809 -0.11849937 -0.09369672 ...         inf  7.3936926
   3.18630945]
 [-0.53520204 -0.26887227  0.15747429 ...  7.3936926          inf
   7.03558948]
 [-0.17809181 -0.4484676   0.21385675 ...  3.18630945  7.03558948
          inf]]
hw95 :  [[        inf  1.13447454  1.61853942 ... -0.35251809 -0.53520204
  -0.17809181]
 [ 1.13447454         inf  2.96866629 ... -0.11849937 -0.26887227
  -0.4484676 ]
 [ 1.61853942  2.96866629         inf ... -0.09369672  0.15747429
   0.21385675]
 ...
 [-0.35251809 -0.11849937 -0.09369672 ...         inf  7.3936926
   3.18630945]
 [-0.53520204 -0.26887227  0.15747429 ...  7.3936926          inf
   7.03558948]
 [-0.17809181 -0.4484676   0.21385675 ...  3.18630945  7.03558948
          inf]]
hy

jw73 :  [[            inf  2.35417525e+00  2.78682539e+00 ... -4.65184051e-01
  -5.26589036e-01 -7.39236521e-02]
 [ 2.35417525e+00             inf  5.14228062e+00 ...  7.86633560e-02
   5.30405138e-02 -3.07485154e-01]
 [ 2.78682539e+00  5.14228062e+00             inf ... -3.90644116e-01
   6.97991099e-03  6.48866603e-02]
 ...
 [-4.65184051e-01  7.86633560e-02 -3.90644116e-01 ...             inf
   1.27658094e+01  5.21661697e+00]
 [-5.26589036e-01  5.30405138e-02  6.97991099e-03 ...  1.27658094e+01
              inf  1.24420414e+01]
 [-7.39236521e-02 -3.07485154e-01  6.48866603e-02 ...  5.21661697e+00
   1.24420414e+01             inf]]
jw73 :  [[            inf  2.35417525e+00  2.78682539e+00 ... -4.65184051e-01
  -5.26589036e-01 -7.39236521e-02]
 [ 2.35417525e+00             inf  5.14228062e+00 ...  7.86633560e-02
   5.30405138e-02 -3.07485154e-01]
 [ 2.78682539e+00  5.14228062e+00             inf ... -3.90644116e-01
   6.97991099e-03  6.48866603e-02]
 ...
 [-4.65184051e-01  7.8663356

tt42 :  [[        inf  3.76676815  3.76503453 ... -0.44503421 -0.38342537
  -0.36654804]
 [ 3.76676815         inf  7.70236316 ...  0.32641593  0.37746345
  -0.27734154]
 [ 3.76503453  7.70236316         inf ... -0.51447268 -0.10172156
  -0.23466843]
 ...
 [-0.44503421  0.32641593 -0.51447268 ...         inf 19.14158138
   8.18292001]
 [-0.38342537  0.37746345 -0.10172156 ... 19.14158138         inf
  19.56755023]
 [-0.36654804 -0.27734154 -0.23466843 ...  8.18292001 19.56755023
          inf]]
tt42 :  [[        inf  3.76676815  3.76503453 ... -0.44503421 -0.38342537
  -0.36654804]
 [ 3.76676815         inf  7.70236316 ...  0.32641593  0.37746345
  -0.27734154]
 [ 3.76503453  7.70236316         inf ... -0.51447268 -0.10172156
  -0.23466843]
 ...
 [-0.44503421  0.32641593 -0.51447268 ...         inf 19.14158138
   8.18292001]
 [-0.38342537  0.37746345 -0.10172156 ... 19.14158138         inf
  19.56755023]
 [-0.36654804 -0.27734154 -0.23466843 ...  8.18292001 19.56755023
          inf]]


Placebo baseline

In [38]:
# first matrix of zeros
A = np.zeros((11883,11883))
count=0
for subj in subj_placebo_new :
    # only loads ketamine subjects in baseline
    file_name = 'corr_mat_all_ses-baseline_sub-' + subj + '.csv'
    # path of the current subject
    curr_subj_path = os.path.join(path_baseline, file_name)
    # read in current subject as dataframe
    # correlated timecourses of each participant
    curr_subj_df = pd.read_csv(curr_subj_path, header=None)
    # change dataframe to numpy array
    curr_sub = curr_subj_df.to_numpy()
    z_curr_sub = np.arctanh(curr_sub)
    mean_mat = np.add(z_curr_sub, A)
    print(subj, ': ' , mean_mat)
    # making proper copy of mean_mat
    A = mean_mat.copy()
    count+=1
    print(subj, ': ' , mean_mat)
    
# saving matrices 
#np.save('C:/Users/canlab/Desktop/Masterthesis_python/baseline/Baseline_p_z_FC_added', mean_mat)
mean_mat_baseline_p = mean_mat / len(subj_placebo_new)  
np.save('C:/Users/canlab/Desktop/Masterthesis_python/ReDoneAnalysis20200420/Placebo/Baseline_p_z_mean_FC', mean_mat_baseline_p)

C:\Users\canlab\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in arctanh
  


ap75 :  [[        inf  0.23671998 -0.0079099  ... -0.02840506  0.00270642
  -0.17666799]
 [ 0.23671998         inf  0.25489854 ...  0.08735687  0.11873444
  -0.0772284 ]
 [-0.0079099   0.25489854         inf ... -0.05737735 -0.00104696
  -0.01665306]
 ...
 [-0.02840506  0.08735687 -0.05737735 ...         inf  0.43622304
  -0.01454103]
 [ 0.00270642  0.11873444 -0.00104696 ...  0.43622304         inf
   0.39024565]
 [-0.17666799 -0.0772284  -0.01665306 ... -0.01454103  0.39024565
          inf]]
ap75 :  [[        inf  0.23671998 -0.0079099  ... -0.02840506  0.00270642
  -0.17666799]
 [ 0.23671998         inf  0.25489854 ...  0.08735687  0.11873444
  -0.0772284 ]
 [-0.0079099   0.25489854         inf ... -0.05737735 -0.00104696
  -0.01665306]
 ...
 [-0.02840506  0.08735687 -0.05737735 ...         inf  0.43622304
  -0.01454103]
 [ 0.00270642  0.11873444 -0.00104696 ...  0.43622304         inf
   0.39024565]
 [-0.17666799 -0.0772284  -0.01665306 ... -0.01454103  0.39024565
          inf]]


em60 :  [[        inf  2.03628691  0.95340756 ... -0.10876077 -0.04756989
  -0.24203839]
 [ 2.03628691         inf  2.13063016 ...  0.05702553  0.02448695
  -0.26760037]
 [ 0.95340756  2.13063016         inf ... -0.04695238 -0.08061967
  -0.22122023]
 ...
 [-0.10876077  0.05702553 -0.04695238 ...         inf  6.61891271
   1.94975753]
 [-0.04756989  0.02448695 -0.08061967 ...  6.61891271         inf
   5.80104646]
 [-0.24203839 -0.26760037 -0.22122023 ...  1.94975753  5.80104646
          inf]]
ew27 :  [[            inf  2.25573360e+00  1.13840336e+00 ... -4.49055653e-03
   3.46633743e-02 -2.10955967e-01]
 [ 2.25573360e+00             inf  2.37667154e+00 ...  3.04943900e-01
   2.90352904e-01 -4.16455762e-01]
 [ 1.13840336e+00  2.37667154e+00             inf ...  1.42477021e-01
   1.72161317e-01 -1.79619682e-01]
 ...
 [-4.49055653e-03  3.04943900e-01  1.42477021e-01 ...             inf
   7.48800574e+00  1.81208756e+00]
 [ 3.46633743e-02  2.90352904e-01  1.72161317e-01 ...  7.48800574e+

kt10 :  [[        inf  4.5512576   2.03724792 ...  0.28372183  0.24321407
   0.08528754]
 [ 4.5512576          inf  4.43274614 ...  0.20860281 -0.14882793
  -0.97011071]
 [ 2.03724792  4.43274614         inf ...  0.23124901  0.44353634
  -0.12172517]
 ...
 [ 0.28372183  0.20860281  0.23124901 ...         inf 12.11634104
   3.56516614]
 [ 0.24321407 -0.14882793  0.44353634 ... 12.11634104         inf
  11.35735173]
 [ 0.08528754 -0.97011071 -0.12172517 ...  3.56516614 11.35735173
          inf]]
ld98 :  [[            inf  5.00741265e+00  2.10295010e+00 ...  2.52053059e-01
   1.56684102e-01 -7.11051581e-04]
 [ 5.00741265e+00             inf  4.71786474e+00 ...  2.72730495e-01
  -4.43856120e-02 -8.83050501e-01]
 [ 2.10295010e+00  4.71786474e+00             inf ...  2.39326020e-01
   5.17718161e-01 -8.48068057e-02]
 ...
 [ 2.52053059e-01  2.72730495e-01  2.39326020e-01 ...             inf
   1.27144655e+01  3.70688653e+00]
 [ 1.56684102e-01 -4.43856120e-02  5.17718161e-01 ...  1.27144655e+

uh70 :  [[        inf  6.12057182  2.63971227 ...  0.20581952  0.38564302
  -0.43133016]
 [ 6.12057182         inf  5.66668531 ...  0.0655429  -0.29819543
  -0.61285887]
 [ 2.63971227  5.66668531         inf ...  0.10993587  0.22080677
  -0.48766188]
 ...
 [ 0.20581952  0.0655429   0.10993587 ...         inf 19.02554017
   7.12247306]
 [ 0.38564302 -0.29819543  0.22080677 ... 19.02554017         inf
  17.5801944 ]
 [-0.43133016 -0.61285887 -0.48766188 ...  7.12247306 17.5801944
          inf]]
vu42 :  [[            inf  6.62857978e+00  2.51659715e+00 ...  3.25981854e-01
   5.18053248e-01 -1.82973914e-01]
 [ 6.62857978e+00             inf  5.75091698e+00 ...  2.85602677e-01
  -1.29699092e-01 -3.35312050e-01]
 [ 2.51659715e+00  5.75091698e+00             inf ... -1.74777373e-02
   2.92762638e-02 -7.59148992e-01]
 ...
 [ 3.25981854e-01  2.85602677e-01 -1.74777373e-02 ...             inf
   1.95748677e+01  7.36557415e+00]
 [ 5.18053248e-01 -1.29699092e-01  2.92762638e-02 ...  1.95748677e+0

In [19]:
mean_mat_baseline_p

array([[        inf,  0.26829097,  0.10764058, ...,  0.00862008,
         0.01913917, -0.01481287],
       [ 0.26829097,         inf,  0.23053835, ...,  0.01211898,
         0.0069263 ,  0.00308682],
       [ 0.10764058,  0.23053835,         inf, ...,  0.01053156,
         0.0096468 , -0.01151348],
       ...,
       [ 0.00862008,  0.01211898,  0.01053156, ...,         inf,
         0.75688051,  0.28337023],
       [ 0.01913917,  0.0069263 ,  0.0096468 , ...,  0.75688051,
                inf,  0.70104278],
       [-0.01481287,  0.00308682, -0.01151348, ...,  0.28337023,
         0.70104278,         inf]])

In [20]:
mean_mat

array([[        inf,  7.78043803,  3.12157678, ...,  0.24998227,
         0.555036  , -0.42957322],
       [ 7.78043803,         inf,  6.68561218, ...,  0.35145038,
         0.20086272,  0.08951791],
       [ 3.12157678,  6.68561218,         inf, ...,  0.30541521,
         0.2797571 , -0.33389104],
       ...,
       [ 0.24998227,  0.35145038,  0.30541521, ...,         inf,
        21.94953487,  8.2177368 ],
       [ 0.555036  ,  0.20086272,  0.2797571 , ..., 21.94953487,
                inf, 20.33024056],
       [-0.42957322,  0.08951791, -0.33389104, ...,  8.2177368 ,
        20.33024056,         inf]])