## Calculating Pearson correlation distance

Script: calculates distance from Pearson correlation

Input: Pearson FC matrix 11883 x 11883 

In [ ]:
#import multiprocessing as mp
import pandas as pd
import numpy as np
from scipy.spatial import distance
from sklearn.metrics import pairwise_distances

In [2]:
data_path = 'C:/Users/canlab/Desktop/Masterthesis_python/z_m_corr_mat_baseline.csv'
corr_mat = pd.read_csv(data_path, engine='c', header = None).astype('float32') 

In [3]:
pd.set_option('use_inf_as_na', True)

In [4]:
corr_mat_df = corr_mat.fillna(1)

In [5]:
display(corr_mat_df)

0         1         2         3         4         5         6      \
0      1.000000  0.190073  0.122199 -0.010400  0.044782  0.037398  0.009948   
1      0.190073  1.000000  0.244537 -0.010937  0.132719  0.054796  0.039224   
2      0.122199  0.244537  1.000000  0.250677 -0.002058  0.046859  0.026447   
3     -0.010400 -0.010937  0.250677  1.000000  0.331399  0.011331  0.008701   
4      0.044782  0.132719 -0.002058  0.331399  1.000000 -0.015189  0.002348   
...         ...       ...       ...       ...       ...       ...       ...   
11878  0.013869 -0.000737 -0.004516  0.019299  0.017295 -0.007111 -0.015374   
11879 -0.003903 -0.025141 -0.028596  0.030204  0.023149 -0.016098 -0.026550   
11880 -0.002313  0.010625 -0.013283  0.016708  0.014547 -0.000638 -0.013855   
11881  0.000121  0.001388  0.004177  0.011591 -0.006427 -0.006504 -0.003753   
11882 -0.021729 -0.023266 -0.024168 -0.010190 -0.023637 -0.028520 -0.013013   

          7         8         9      ...     11873     11874     11875  \
0      0.017958 -0.031793  0.002940  ... -0.023032 -0.008735 -0.023229   
1      0.039553  0.034149  0.085658  ... -0.015646  0.000505 -0.016302   
2      0.047875 -0.019307  0.053231  ... -0.005958 -0.003891  0.002164   
3      0.004794  0.032620  0.012360  ...  0.023866 -0.040187  0.017664   
4      0.014416  0.045493  0.022873  ...  0.007388 -0.039979  0.016427   
...         ...       ...       ...  ...       ...       ...       ...   
11878  0.012407  0.009968 -0.013990  ...  0.232212  0.197342  0.207674   
11879  0.008925  0.019954 -0.025964  ...  0.253280  0.211977  0.220728   
11880 -0.002925  0.020974 -0.010081  ...  0.217154  0.226576  0.184357   
11881  0.012275  0.002049 -0.019449  ...  0.192376  0.238928  0.178672   
11882  0.002905  0.003055 -0.030122  ...  0.197732  0.228757  0.190368   

          11876     11877     11878     11879     11880     11881     11882  
0      0.004165 -0.018986  0.013869 -0.003903 -0.002313  0.000121 -0.021729  
1      0.007040 -0.019177 -0.000737 -0.025141  0.010625  0.001388 -0.023266  
2      0.001176 -0.017871 -0.004516 -0.028596 -0.013283  0.004177 -0.024168  
3     -0.018539  0.029983  0.019299  0.030204  0.016708  0.011591 -0.010190  
4     -0.035929  0.015849  0.017295  0.023149  0.014547 -0.006427 -0.023637  
...         ...       ...       ...       ...       ...       ...       ...  
11878  0.221070  0.161816  1.000000  0.789299  0.336485  0.291064  0.250657  
11879  0.211267  0.186178  0.789299  1.000000  0.717094  0.303201  0.309652  
11880  0.226611  0.179102  0.336485  0.717094  1.000000  0.744356  0.311368  
11881  0.226127  0.163393  0.291064  0.303201  0.744356  1.000000  0.752035  
11882  0.201977  0.176650  0.250657  0.309652  0.311368  0.752035  1.000000  

[11883 rows x 11883 columns]

In [7]:
FC_mat = corr_mat_df.to_numpy()

In [8]:
FC_mat

array([[ 1.0000000e+00,  1.9007330e-01,  1.2219934e-01, ...,
        -2.3133066e-03,  1.2110837e-04, -2.1729171e-02],
       [ 1.9007330e-01,  1.0000000e+00,  2.4453712e-01, ...,
         1.0625493e-02,  1.3884309e-03, -2.3265786e-02],
       [ 1.2219934e-01,  2.4453712e-01,  1.0000000e+00, ...,
        -1.3282697e-02,  4.1772407e-03, -2.4167635e-02],
       ...,
       [-2.3133066e-03,  1.0625493e-02, -1.3282697e-02, ...,
         1.0000000e+00,  7.4435574e-01,  3.1136835e-01],
       [ 1.2110837e-04,  1.3884309e-03,  4.1772407e-03, ...,
         7.4435574e-01,  1.0000000e+00,  7.5203472e-01],
       [-2.1729171e-02, -2.3265786e-02, -2.4167635e-02, ...,
         3.1136835e-01,  7.5203472e-01,  1.0000000e+00]], dtype=float32)

In [9]:
corr_vec = np.zeros((11883, 11883), dtype='float')

In [10]:
corr_vec

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
def calculate_corr_distance():

    #corr_vec[i,j] = distance.correlation(u,v)
    #corr_vec = distance.pdist(FC_mat, 'correlation')
    #corr_coef_mat = np.corrcoef(FC_mat)
    #corr_vec = pairwise_distances(FC_mat, metric = 'correlation')
    corr_vec = 1 - np.corrcoef(FC_mat)
    np.save('C:/Users/canlab/Desktop/Masterthesis_python/corr_distance', corr_vec)

    return corr_vec

In [19]:
co_dist = calculate_corr_distance()

In [15]:
cor.shape

(11883, 11883)

In [20]:
co_dist

array([[0.00000000e+00, 6.67595526e-01, 6.07826794e-01, ...,
        1.02349204e+00, 1.00602072e+00, 1.06806415e+00],
       [6.67595526e-01, 0.00000000e+00, 6.15815186e-01, ...,
        1.01088712e+00, 1.04667645e+00, 1.13025687e+00],
       [6.07826794e-01, 6.15815186e-01, 0.00000000e+00, ...,
        1.03821633e+00, 9.97420346e-01, 1.06777580e+00],
       ...,
       [1.02349204e+00, 1.01088712e+00, 1.03821633e+00, ...,
        2.22044605e-16, 9.14650760e-02, 2.08707693e-01],
       [1.00602072e+00, 1.04667645e+00, 9.97420346e-01, ...,
        9.14650760e-02, 0.00000000e+00, 9.85301828e-02],
       [1.06806415e+00, 1.13025687e+00, 1.06777580e+00, ...,
        2.08707693e-01, 9.85301828e-02, 0.00000000e+00]])

In [22]:
cor

array([[ 1.        ,  0.33240447,  0.39217321, ..., -0.02349204,
        -0.00602072, -0.06806415],
       [ 0.33240447,  1.        ,  0.38418481, ..., -0.01088712,
        -0.04667645, -0.13025687],
       [ 0.39217321,  0.38418481,  1.        , ..., -0.03821633,
         0.00257965, -0.0677758 ],
       ...,
       [-0.02349204, -0.01088712, -0.03821633, ...,  1.        ,
         0.90853492,  0.79129231],
       [-0.00602072, -0.04667645,  0.00257965, ...,  0.90853492,
         1.        ,  0.90146982],
       [-0.06806415, -0.13025687, -0.0677758 , ...,  0.79129231,
         0.90146982,  1.        ]])

In [12]:
pool = mp.Pool(mp.cpu_count())

In [ ]:
corr_vec = [pool.apply(calculate_corr_distance)]
pool.close()  

In [13]:
mp.cpu_count()

8

In [ ]:
np.save('C:/Users/canlab/Desktop/Masterthesis_python/corr_vec', corr_vec)

In [ ]:
result = calculate_corr_distance()
np.save('C:/Users/canlab/Desktop/Masterthesis_python/result', result)